### ISSUE TITLE
Possible fatal error?

### ISSUE THREAD

**Issue by VaelophisNyx** [KingEnderBrine/-RoR2-ScrollableLobbyUI#2]
`[Error  : Unity Log] IndexOutOfRangeException: NetworkReader:ReadByte out of range:NetBuf sz:58 pos:58
Stack trace:
UnityEngine.Networking.NetBuffer.ReadByte () (at <73dce905efe04cb5acf013e51496d921>:IL_0022)
UnityEngine.Networking.NetworkReader.ReadByte () (at <73dce905efe04cb5acf013e51496d921>:IL_0000)
UnityEngine.Networking.NetworkReader.ReadPackedUInt32 () (at <73dce905efe04cb5acf013e51496d921>:IL_0000)
RoR2.Loadout+BodyLoadoutManager+BodyLoadout.Deserialize (UnityEngine.Networking.NetworkReader reader) (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0036)
RoR2.Loadout+BodyLoadoutManager.Deserialize (UnityEngine.Networking.NetworkReader reader) (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0051)
RoR2.Loadout.Deserialize (UnityEngine.Networking.NetworkReader reader) (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0000)
RoR2.Networking.NetworkLoadout.OnDeserialize (UnityEngine.Networking.NetworkReader reader, System.Boolean initialState) (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_000A)
UnityEngine.Networking.NetworkIdentity.OnUpdateVars (UnityEngine.Networking.NetworkReader reader, System.Boolean initialState) (at <73dce905efe04cb5acf013e51496d921>:IL_001B)
UnityEngine.Networking.ClientScene.OnUpdateVarsMessage (UnityEngine.Networking.NetworkMessage netMsg) (at <73dce905efe04cb5acf013e51496d921>:IL_0059)
UnityEngine.Networking.NetworkConnection.HandleReader (UnityEngine.Networking.NetworkReader reader, System.Int32 receivedSize, System.Int32 channelId) (at <73dce905efe04cb5acf013e51496d921>:IL_010B)
UnityEngine.Networking.NetworkConnection.HandleBytes (System.Byte[] buffer, System.Int32 receivedSize, System.Int32 channelId) (at <73dce905efe04cb5acf013e51496d921>:IL_0007)
UnityEngine.Networking.NetworkConnection.TransportReceive (System.Byte[] bytes, System.Int32 numBytes, System.Int32 channelId) (at <73dce905efe04cb5acf013e51496d921>:IL_0000)
RoR2.Networking.SteamNetworkConnection.TransportReceive (System.Byte[] bytes, System.Int32 numBytes, System.Int32 channelId) (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0019)
RoR2.Networking.GameNetworkManager.OnP2PData (Facepunch.Steamworks.BaseSteamworks receiver, CSteamID senderSteamId, System.Byte[] data, System.Int32 dataLength, System.Int32 channel) (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0044)
RoR2.Networking.GameNetworkManager.OnSteamClientP2PData (System.UInt64 senderSteamId, System.Byte[] data, System.Int32 dataLength, System.Int32 channel) (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_000C)
Facepunch.Steamworks.Networking.ReadP2PPacket (System.Int32 channel) (at <d83e4fb44ee848ed810344c6c4815aae>:IL_0082)
Facepunch.Steamworks.Networking.Update () (at <d83e4fb44ee848ed810344c6c4815aae>:IL_0054)
Facepunch.Steamworks.BaseSteamworks.Update () (at <d83e4fb44ee848ed810344c6c4815aae>:IL_0006)
Facepunch.Steamworks.Client.Update () (at <d83e4fb44ee848ed810344c6c4815aae>:IL_0025)
RoR2.SteamworksClientManager.Update () (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0000)
RoR2.RoR2Application.Update () (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0053)
`
Cant figure out what is causing it, but clients cant change characters,  vote on artifacts, or ready up at all, and starting multiplayer via the 1m timer, just leaves clients at the character select screen.

**Comment by VaelophisNyx** [comment]
actually, removing this somehow managed to make this worse! clients dont exist for themselves now, and have no visible characters at all!

**Comment by KingEnderBrine** [comment]
Not an issue with `ScrollableLobbyUI`, it's something to do with networking. You probably have different mods or configs, or some mods don't work in mp, it's nothing to do with this mod. You should go to RoR2 modding discord to `#tech-support` channel.

**Comment by VaelophisNyx** [comment]
I figured, after the issue got worse. I'd love to go there, but they refuse to oust people who think slurs are funny, and being assholes is cool .^.

apologies, and thanks
