### ISSUE TITLE
Mod incompatible after recent DLC

### ISSUE THREAD

**Issue by CrystalGemHeliotrope** [KingEnderBrine/-RoR2-ScrollableLobbyUI#3]
I honestly wish to know if this is being worked on or not? This mod is what helps make it possible to have loads of modded characters installed to Risk of Rain 2 without having them go all the way off screen.

**Comment by KingEnderBrine** [comment]
Yes' I'm working on it

**Comment by CrystalGemHeliotrope** [comment]
> Yes' I'm working on it

Nice! Thank you.

**Comment by KingEnderBrine** [comment]
Published an update
