### ISSUE TITLE
Config to disable changes to Character Select / Compatibility with 3rdRowCSS

### ISSUE THREAD

**Issue by gaforb** [KingEnderBrine/-RoR2-ScrollableLobbyUI#4]
Honestly something as simple as config to disable changes to the Character Selector (while leaving scrolling in all other fields) would be enough, since I don't think most people have more than 24 survivors anyway, but anything more advanced than that (like adding a third row internally or only adding the arrows if more than 14 characters are detected) would be fantastic.

**Comment by KingEnderBrine** [comment]
Compatibility with `3rdRowCSS` would be silly as I have full control over how many rows there are, I can just add a config for that. I will consider having arrows be hidden if everything can fit into a single page.

**Comment by KingEnderBrine** [comment]
Published an update, added config to select the amount of rows shown, arrows are hidden if all survivors fit into a single page
