### ISSUE TITLE
Log book breaks after installing the mod.

### ISSUE THREAD

**Issue by DatSpygineer** [KingEnderBrine/-RoR2-ScrollableLobbyUI#5]
Hello! I've installed your mod and it broke the log book and it stays broken even if I disable all the mods. (Works fine if launched vanilla)
![image](https://user-images.githubusercontent.com/61582587/164266529-24154647-62a4-4c5b-88c2-d63615f61a0b.png)

**Comment by DatSpygineer** [comment]
Oh and I forget to post the log.
[LogOutput.log](https://github.com/KingEnderBrine/-RoR2-ScrollableLobbyUI/files/8522964/LogOutput.log)

**Comment by KingEnderBrine** [comment]
It's an issue with vanilla code, it breaks achievements if a mod has optional dependencies. There's nothing I can do about, but installing `InLobbyConfig` should fix it for `ScrollableLobbyUI`.
