### ISSUE TITLE
Scrolling Breaks The Character Select

### ISSUE THREAD

**Issue by Memory-Dot-Wipe** [KingEnderBrine/-RoR2-ScrollableLobbyUI#8]
A good thing to preface this with is that i only use a "Bare Bones" Modlist, and i have checked with and without, the Scrolling is the trouble. as i can only assume the newest update with the DLC has broken it. (Mind you i don't even use the newest DLC so who knows it might also be that i need the dlc for this to work anymore.)

**Comment by CursedWolf** [comment]
Nah, with DLC i have, scrolling is broken. Without it, i can't choose Enforcer ;(

**Comment by KingEnderBrine** [comment]
Published an update for the dlc update
