### ISSUE TITLE
Vertical Scroll Config Suggestion

### ISSUE THREAD

**Issue by MysticaIChicken** [KingEnderBrine/-RoR2-ScrollableLobbyUI#9]
The `SkillsSkinsWheelScrolling` config works exactly as expected for _rows_ of skills or skins. However, would it be possible to add a config option to disable _column_ scrolling for the skills and skins? Vanilla example this would effect would be Captain, with his double beacons causing a scroll requirement by default. 
![image](https://github.com/user-attachments/assets/fd182edc-c11b-4a07-8a48-dcd0196d22dd)
![image](https://github.com/user-attachments/assets/e3a27c75-fe15-49c6-9868-50fb510c1409)

**Comment by KingEnderBrine** [comment]
I wont add that. What I can add however is an option to change rows height, so you can set it to something where you see enough, but still will be able to have scrolling if there is just too much rows.

**Comment by KingEnderBrine** [comment]
Published an update with config option to change row height. Setting it to something like 64 should be enough to fit all Captain's skills

**Comment by MysticaIChicken** [comment]
Fair enough, sounds good. I will look at it later today. Out of curiousity, would this result in dead space for other characters with less skills than Captain if set to 64, or would it resize to a minimum in order to fill the UI? Either way, thanks for the quick response and work!

**Comment by KingEnderBrine** [comment]
It would leave empty space.
